---
- name: create systemd service file
  copy:
    src: ../files/minecraft.service
    dest: /etc/systemd/system
    owner: root
    group: root

- name: enable and start the minecraft service
  systemd:
    name: minecraft.service
    enabled: true
    state: started
    daemon_reload: true